#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
function dd(... $arguments)
{
    foreach ($arguments as $argument) {
        var_dump($argument);
    }
    die;
}

use Homeapp\OpenapiGenerator\Command\CreateDTO;
use Nette\PhpGenerator\Printer;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CreateDTO(null, new Printer()));

$application->run();